# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main
  push:
    
defaults:
  run:
    shell: bash
    working-directory: workdir

jobs:
  test:
    runs-on: ubuntu-lastest
    defaults: 
      run:
        shell: sh
        working-directory: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "in test"
